name: gihub_action
on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Test maven
        run: mvn test

      - name: checkstyle
        run: mvn checkstyle:checkstyle